version: '3.4'

services:
  cache-data:
    restart: always
    ports:
      - "6379:6379"

  catalogue-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AppSettings__DbConnection=test_db
      - AppSettings__ApiKeys__0=test_1
      - AppSettings__ApiKeys__1=test_2
      - AppSettings__ComplexItems__0__Identifier=identifier_1
      - AppSettings__ComplexItems__0__Password=password_1
      - AppSettings__ComplexItems__1__Identifier=identifier_2
      - AppSettings__ComplexItems__1__Password=password_2
    ports:
      - "37001:80"

  panier-api-1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "37002:80"

  panier-api-2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "37003:80"
