version: '3.4'

services:
  catalogue-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AppSettings__DbConnection=test_db
      - AppSettings__ApiKeys__0=test_1
      - AppSettings__ApiKeys__1=test_2
      - AppSettings__ComplexItems__0__Identifier=identifier_1
      - AppSettings__ComplexItems__0__Password=password_1
      - AppSettings__ComplexItems__1__Identifier=identifier_2
      - AppSettings__ComplexItems__1__Password=password_2
    ports:
      - "37001:80"
