version: '3.4'

services:
  sql-data:
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - formation-sqldata:/var/lib/postgresql/data

  cache-data:
    restart: always
    ports:
      - "6379:6379"

  catalogue-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "37001:80"
      - "37011:81"

  panier-api-1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "37002:80"

  panier-api-2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "37003:80"

volumes:
  formation-sqldata:
    external: true