// <auto-generated />
using System;
using Catalogue.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Catalogue.API.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogueContext))]
    partial class CatalogueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Catalogue.API.Models.Famille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_famille");

                    b.ToTable("famille");
                });

            modelBuilder.Entity("Catalogue.API.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("FamilleId")
                        .HasColumnType("integer")
                        .HasColumnName("famille_id");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("libelle");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("pk_produits");

                    b.HasIndex("FamilleId")
                        .HasDatabaseName("ix_produits_famille_id");

                    b.ToTable("produits");
                });

            modelBuilder.Entity("Catalogue.API.Models.Produit", b =>
                {
                    b.HasOne("Catalogue.API.Models.Famille", "Famille")
                        .WithMany()
                        .HasForeignKey("FamilleId")
                        .HasConstraintName("fk_produits_famille_famille_id");

                    b.Navigation("Famille");
                });
#pragma warning restore 612, 618
        }
    }
}
